### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'items'

### ISSUE THREAD

**Issue by ssozonoff** [Guavus/incubator-superset#34]
Hi,

Got everything setup and running but unable to refresh Elastic Metadata.
Getting the following error

`superset_1  | 2018-12-15 18:34:48,436:INFO:root:Syncing Elastic datasource [v3-blocks_2018_trial._default_]
superset_1  | 2018-12-15 18:34:48,453:ERROR:root:'NoneType' object has no attribute 'items'
superset_1  | Traceback (most recent call last):
superset_1  |   File "/home/work/incubator-superset/superset/connectors/elastic/views.py", line 268, in refresh_datasources
superset_1  |     cluster.refresh_datasources()
superset_1  |   File "/home/work/incubator-superset/superset/connectors/elastic/models.py", line 73, in refresh_datasources
superset_1  |     '{}.{}'.format(index_name, name), mapping_metadata, self)
superset_1  |   File "/home/work/incubator-superset/superset/connectors/elastic/models.py", line 425, in sync_to_db
superset_1  |     for col_name, col_metadata in metadata.get('properties').items():
superset_1  | AttributeError: 'NoneType' object has no attribute 'items'`

What Elasticsearch version do you currently support. I am running ES 6.x

Thanks

**Comment by arpit-agarwal** [comment]
We support ES 5.3 at this point of time.

**Comment by ssozonoff** [comment]
OK Thanks. Not sure the issue I mentioned above is specific to ES6. Seems there is an assumption made about the properties always being available when they are in fact optional.

**Comment by ssozonoff** [comment]
OK I was able to get past this issue with an if statement but run into other problems later on. If I have time I will look into it further.
